# China domain list - primary source
# https://github.com/P100001000/chnroute
TYPE=chnlist
PRIMARY=https://raw.githubusercontent.com/P100001000/chnroute/main/mosdns_chnlist/Domains.chn.txt
MIRROR=https://ghproxy.net/https://raw.githubusercontent.com/P100001000/chnroute/main/mosdns_chnlist/Domains.chn.txt
SHA=https://raw.githubusercontent.com/P100001000/chnroute/main/mosdns_chnlist/Domains.chn.txt.sha256sum
