# China domain list - secondary source (dnsmasq format, auto-converted)
# https://github.com/felixonmars/dnsmasq-china-list
TYPE=chnlist
PRIMARY=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
MIRROR=https://ghproxy.net/https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
SHA=none
FORMAT=dnsmasq-server
