#!/bin/bash
unset publicIPurls
publicIPurls+=(http://cip.cc)
publicIPurls+=(https://v4.yinghualuo.cn/bejson)
publicIPurls+=(http://myip.ipip.net)

for (( i=0; i<10; ++i)); do
	wanIP=$(curl -fsLm 2 ${publicIPurls[$RANDOM % ${#publicIPurls[@]}]} 2>/dev/null)
	[[ $wanIP == *移动* ]] && wanIP=""
	wanIP=$(echo $wanIP | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -n1)
	[[ -n $wanIP ]] && [[ -z $(nft get element ip de_GWD CHNROUTE { $wanIP } 2>&1 | grep 'Error:') ]] && break
	wanIP=""
	sleep 1
done

echo $wanIP
